---
- name: Gather and summarize cron jobs across all users with a /home directory
  hosts: all
  become: true
  gather_facts: false

  vars:
    users_with_crontabs: []
    root_has_crontab: false

  tasks:
    - name: Get list of users with a /home directory
      command: ls /home
      register: home_users

    - name: Get cron jobs for each user
      command: crontab -u {{ item }} -l
      register: user_crontab
      ignore_errors: true
      loop: "{{ home_users.stdout_lines }}"
      changed_when: user_crontab.rc == 0
      no_log: true

    - name: Mark users with crontabs
      set_fact:
        users_with_crontabs: "{{ users_with_crontabs + [item] }}"
      when: user_crontab.rc == 0
      loop: "{{ home_users.stdout_lines }}"
      loop_control:
        index_var: idx
      vars:
        user_crontab: "{{ user_crontab.results[idx] }}"

    - name: Get root user's cron jobs
      command: sudo crontab -u root -l
      register: root_crontab
      ignore_errors: true
      changed_when: root_crontab.rc == 0
      no_log: true

    - name: Mark root user with crontab
      set_fact:
        root_has_crontab: true
      when: root_crontab.rc == 0

    - name: Summarize cron jobs for users with crontabs
      debug:
        msg: "User {{ item }}'s crontab:\n{{ lookup('file', '/var/spool/cron/crontabs/' + item) }}"
      loop: "{{ users_with_crontabs }}"

    - name: Summarize root user's cron jobs
      debug:
        msg: "Root user's crontab:\n{{ root_crontab.stdout }}"
      when: root_has_crontab

    - name: Summarize users without crontabs
      debug:
        msg: "User {{ item }} has no crontab."
      when: item not in users_with_crontabs
      loop: "{{ home_users.stdout_lines }}"

    - name: Get system-wide crontab
      command: cat /etc/crontab
      register: system_crontab
      ignore_errors: true

    - name: Summarize system-wide crontab
      debug:
        msg: "System-wide crontab:\n{{ system_crontab.stdout }}"
      when: system_crontab.stdout is defined

    - name: List files in /etc/cron.d
      command: ls /etc/cron.d
      register: cron_d_files
      ignore_errors: true

    - name: Get contents of each file in /etc/cron.d
      command: cat /etc/cron.d/{{ item }}
      register: cron_d_contents
      ignore_errors: true
      loop: "{{ cron_d_files.stdout_lines }}"

    - name: Summarize /etc/cron.d contents
      debug:
        msg: "/etc/cron.d/{{ item.item }}:\n{{ item.stdout }}"
      when: item.stdout is defined
      loop: "{{ cron_d_contents.results }}"
