---
- name: Gather and summarize cron jobs across all users with a /home directory
  hosts: all
  become: true
  gather_facts: false

  vars:
    cron_summary: []

  tasks:
    - name: Get list of users with a /home directory
      command: ls /home
      register: home_users

    - name: Get cron jobs for each user
      command: crontab -u {{ item }} -l
      register: user_crontab
      ignore_errors: true
      loop: "{{ home_users.stdout_lines }}"
      changed_when: user_crontab.rc == 0

    - name: Get root user's cron jobs
      command: sudo crontab -u root -l
      register: root_crontab
      ignore_errors: true
      changed_when: root_crontab.rc == 0

    - name: Summarize cron jobs for users with a crontab
      debug:
        msg: "User {{ item.item }}'s crontab:\n{{ item.stdout }}"
      when: item.rc == 0
      loop: "{{ user_crontab.results }}"

    - name: Summarize root user's cron jobs
      debug:
        msg: "Root user's crontab:\n{{ root_crontab.stdout }}"
      when: root_crontab.rc == 0
    - name: Get system-wide crontab
      command: cat /etc/crontab
      register: system_crontab
      ignore_errors: true

    - name: List files in /etc/cron.d
      command: ls /etc/cron.d
      register: cron_d_files
      ignore_errors: true

    - name: Get contents of each file in /etc/cron.d
      command: cat /etc/cron.d/{{ item }}
      register: cron_d_contents
      ignore_errors: true
      loop: "{{ cron_d_files.stdout_lines }}"
