---
- name: Run Syft and Grype Test Commands
  hosts: all
  gather_facts: false

  tasks:
    - name: Get image SBOM
      ansible.builtin.shell:
        cmd: syft {{ survey_image }} --scope all-layers -o syft-json
      register: syft_output
