---
- name: Run PiHole maintenance commands
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Update PiHole
      ansible.builtin.command:
        command:
          - "pihole -up"
      register: results

    - name: Update Gravity
      ansible.builtin.command:
        command:
          - "pihole -g"
      register: results