---
- name: Run PiHole maintenance commands
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Run PiHole maintenance commands
      ansible.builtin.shell: |
        pihole status
        pihole version
        pihole updatePihole
        pihole updateGravity
        pihole status
        pihole version
      register: pihole_output

    - name: Print PiHole output
      ansible.builtin.debug:
        msg: "{{ pihole_output.stdout_lines }}"
