---
- name: Run PiHole maintenance commands
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Get Current Status
      ansible.builtin.command:
        cmd: pihole status
          
    - name: Get Current Version
      ansible.builtin.command:
        cmd: pihole version

    - name: Update PiHole
      ansible.builtin.command:
        cmd: pihole updatePihole

    - name: Update Gravity
      ansible.builtin.command:
        cmd: pihole updateGravity

    - name: Get Final Status
      ansible.builtin.command:
        cmd: 
          - pihole status
          - pihole version

    - name: Get Final Version
      ansible.builtin.command:
        cmd: pihole version
