---
- name: Run PiHole maintenance commands
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Get Current Status
      ansible.builtin.command:
        cmd: pihole status

    - name: Update PiHole
      ansible.builtin.command:
        cmd: pihole -up

    - name: Update Gravity
      ansible.builtin.command:
        cmd: pihole -g

    - name: Get Final Status
      ansible.builtin.command:
        cmd: pihole status