---
- name: Run PiHole maintenance commands
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Getting status and updating
      ansible.builtin.shell: |
        pihole status
        pihole version
        pihole updatePihole
        pihole updateGravity
        pihole version
      register: pihole_output

