---
- name: Roll Back Proxmox VM to a Snapshot
  hosts: all
  gather_facts: no

  tasks:

    - name: Stop the VM
      community.general.proxmox:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        vmid: "{{ vmid }}"
        state: stopped  # This will stop the VM
        timeout: 90
      register: stop_result  # Register the output to a variable

    - name: Stop the VM results
      ansible.builtin.debug:
        var: stop_result  # Print the output of the stop VM task
    
    - name: Roll back to snapshot
      community.general.proxmox_snap:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        vmid: "{{ vmid }}"
        snapname: "{{ snapshot_name }}"
        state: rollback
      register: rollback_result  # Register the output to a variable

    - name: Rollback results
      ansible.builtin.debug:
        var: rollback_result  # Print the output of the rollback task

    - name: Start the VM
      community.general.proxmox:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        vmid: "{{ vmid }}"
        state: started  # This will start the VM
        timeout: 90
      register: start_result  # Register the output to a variable

    - name: Start the VM results
      ansible.builtin.debug:
        var: start_result  # Print the output of the start VM task
