---
- name: Roll Back Proxmox VM to a Snapshot
  hosts: all
  gather_facts: no
  tasks:
    - name: Roll back to snapshot
      community.general.proxmox_snap:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        vmid: "{{ vmid }}"
        snapname: "{{ snapshot_name }}"
        timeout: 500
        state: rollback
      register: result

    - name: Print task output
      debug:
        var: result
