---
- name: Roll Back Proxmox VM to a Snapshot
  hosts: all
  gather_facts: no

  tasks:
    - name: Stop the VM using shell command
      shell: "qm stop {{ vmid }}"
      register: stop_result

    - name: Check if VM is stopped
      assert:
        that:
          - stop_result.rc == 0  # Checking the return code of the shell command
        fail_msg: "Stopping the VM failed. Cannot proceed with the rollback."
        success_msg: "VM stopped successfully. Proceeding with the rollback."

    - name: Roll back to snapshot
      community.general.proxmox_snap:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        vmid: "{{ vmid }}"
        snapname: "{{ snapshot_name }}"
        state: rollback
      register: rollback_result
      when: stop_result.rc == 0  # Execute this task only if stopping the VM was successful

    - name: Print rollback result
      ansible.builtin.debug:
        var: rollback_result

    - name: Start the VM using shell command
      shell: "qm start {{ vmid }}"
      register: start_result
      when: rollback_result is success  # Execute this task only if the rollback was successful

    - name: Confirm if VM is started
      assert:
        that:
          - start_result.rc == 0  # Checking the return code of the shell command
        fail_msg: "Starting the VM failed after the rollback."
        success_msg: "VM started successfully after the rollback."
