---
- name: Perform updates to all lab nodes
  hosts: all
  gather_facts: false

  tasks:
    - name: Upgrade distribution and clean / remove unused packages / dependencies
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: true
        autoclean: true
        autoremove: true
        
    - name: Check systemd reboot status
      ansible.builtin.command:
        cmd: systemctl status reboot.target
      register: reboot_status
      ignore_errors: true

    - name: Determine if reboot is required
      ansible.builtin.debug:
        msg: "A reboot is required"
      when: "'inactive' not in reboot_status.stdout"

    - name: Determine if reboot is not required
      ansible.builtin.debug:
        msg: "A reboot is NOT required"
      when: "'inactive' in reboot_status.stdout"

    - name: Compile List of currently logged in users
      ansible.builtin.command:
        cmd: w
      register: users_status

    - name: Schedule reboot in 5 minutes for servers requiring reboot
      ansible.builtin.reboot:
        msg: "ATTENTION: this machine will reboot in 5 minutes to apply updates!"
        pre_reboot_delay: 360
        reboot_timeout: 600
      become: true
      when: "'inactive' not in reboot_status.stdout"
