---
- name: Perform updates to all lab nodes
  hosts: all
  become: true
  become_user: root
  gather_facts: false

  tasks:

  - name: Upgrade distribution and clean / remove unused packages / dependencies
    apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: yes
      autoclean: yes
      autoremove: yes

  - name: Checking if a reboot is needed
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no

  - name: Executing reboot due to kernel update
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 360
      pre_reboot_delay: 0
      post_reboot_delay: 360
      test_command: uptime
    when: reboot_required_file.stat.exists
